const CartActionTypes = {
  TOGGLE_CART_HIDDEN: 'TOGGLE_CART_HIDDEN',
  ADD_ITEM: 'ADD_ITEM',
  REMOVE_CART_ITEM: 'REMOVE_CART_ITEM',
  DECREASE_QUANTITY: 'DECREASE_QUANTITY',
};

export default CartActionTypes;
